### ISSUE TITLE
ML Model Modularity

### ISSUE THREAD

**Issue by danielWatson3141** [danielWatson3141/coderID#6]
Currently, our tool is built around a RFC (Random Forest Classifier). It would be of great value if we could run other algorithms over our dataset to see what we can come across. I would like to see our RFC code abstracted out of the main program and brought into a more genericized class so we can attempt other classification techniques.

**Comment by Azoacha** [comment]
Complete with random forest, SVM, and logistic regression models added in. Model selection can be done via the console, or by directly editing the config.ini file (best method to use if changing the model parameters as well).
